# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jayyang/dev_tools/lz4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jayyang/dev_tools/lz4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jayyang/dev_tools/lz4/CMakeFiles /Users/jayyang/dev_tools/lz4/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jayyang/dev_tools/lz4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lz4

# Build rule for target.
lz4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lz4
.PHONY : lz4

# fast build rule for target.
lz4/fast:
	$(MAKE) -f CMakeFiles/lz4.dir/build.make CMakeFiles/lz4.dir/build
.PHONY : lz4/fast

lz4lib/lz4.o: lz4lib/lz4.c.o

.PHONY : lz4lib/lz4.o

# target to build an object file
lz4lib/lz4.c.o:
	$(MAKE) -f CMakeFiles/lz4.dir/build.make CMakeFiles/lz4.dir/lz4lib/lz4.c.o
.PHONY : lz4lib/lz4.c.o

lz4lib/lz4.i: lz4lib/lz4.c.i

.PHONY : lz4lib/lz4.i

# target to preprocess a source file
lz4lib/lz4.c.i:
	$(MAKE) -f CMakeFiles/lz4.dir/build.make CMakeFiles/lz4.dir/lz4lib/lz4.c.i
.PHONY : lz4lib/lz4.c.i

lz4lib/lz4.s: lz4lib/lz4.c.s

.PHONY : lz4lib/lz4.s

# target to generate assembly for a file
lz4lib/lz4.c.s:
	$(MAKE) -f CMakeFiles/lz4.dir/build.make CMakeFiles/lz4.dir/lz4lib/lz4.c.s
.PHONY : lz4lib/lz4.c.s

lz4lib/lz4frame.o: lz4lib/lz4frame.c.o

.PHONY : lz4lib/lz4frame.o

# target to build an object file
lz4lib/lz4frame.c.o:
	$(MAKE) -f CMakeFiles/lz4.dir/build.make CMakeFiles/lz4.dir/lz4lib/lz4frame.c.o
.PHONY : lz4lib/lz4frame.c.o

lz4lib/lz4frame.i: lz4lib/lz4frame.c.i

.PHONY : lz4lib/lz4frame.i

# target to preprocess a source file
lz4lib/lz4frame.c.i:
	$(MAKE) -f CMakeFiles/lz4.dir/build.make CMakeFiles/lz4.dir/lz4lib/lz4frame.c.i
.PHONY : lz4lib/lz4frame.c.i

lz4lib/lz4frame.s: lz4lib/lz4frame.c.s

.PHONY : lz4lib/lz4frame.s

# target to generate assembly for a file
lz4lib/lz4frame.c.s:
	$(MAKE) -f CMakeFiles/lz4.dir/build.make CMakeFiles/lz4.dir/lz4lib/lz4frame.c.s
.PHONY : lz4lib/lz4frame.c.s

lz4lib/lz4hc.o: lz4lib/lz4hc.c.o

.PHONY : lz4lib/lz4hc.o

# target to build an object file
lz4lib/lz4hc.c.o:
	$(MAKE) -f CMakeFiles/lz4.dir/build.make CMakeFiles/lz4.dir/lz4lib/lz4hc.c.o
.PHONY : lz4lib/lz4hc.c.o

lz4lib/lz4hc.i: lz4lib/lz4hc.c.i

.PHONY : lz4lib/lz4hc.i

# target to preprocess a source file
lz4lib/lz4hc.c.i:
	$(MAKE) -f CMakeFiles/lz4.dir/build.make CMakeFiles/lz4.dir/lz4lib/lz4hc.c.i
.PHONY : lz4lib/lz4hc.c.i

lz4lib/lz4hc.s: lz4lib/lz4hc.c.s

.PHONY : lz4lib/lz4hc.s

# target to generate assembly for a file
lz4lib/lz4hc.c.s:
	$(MAKE) -f CMakeFiles/lz4.dir/build.make CMakeFiles/lz4.dir/lz4lib/lz4hc.c.s
.PHONY : lz4lib/lz4hc.c.s

lz4lib/xxhash.o: lz4lib/xxhash.c.o

.PHONY : lz4lib/xxhash.o

# target to build an object file
lz4lib/xxhash.c.o:
	$(MAKE) -f CMakeFiles/lz4.dir/build.make CMakeFiles/lz4.dir/lz4lib/xxhash.c.o
.PHONY : lz4lib/xxhash.c.o

lz4lib/xxhash.i: lz4lib/xxhash.c.i

.PHONY : lz4lib/xxhash.i

# target to preprocess a source file
lz4lib/xxhash.c.i:
	$(MAKE) -f CMakeFiles/lz4.dir/build.make CMakeFiles/lz4.dir/lz4lib/xxhash.c.i
.PHONY : lz4lib/xxhash.c.i

lz4lib/xxhash.s: lz4lib/xxhash.c.s

.PHONY : lz4lib/xxhash.s

# target to generate assembly for a file
lz4lib/xxhash.c.s:
	$(MAKE) -f CMakeFiles/lz4.dir/build.make CMakeFiles/lz4.dir/lz4lib/xxhash.c.s
.PHONY : lz4lib/xxhash.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... lz4"
	@echo "... lz4lib/lz4.o"
	@echo "... lz4lib/lz4.i"
	@echo "... lz4lib/lz4.s"
	@echo "... lz4lib/lz4frame.o"
	@echo "... lz4lib/lz4frame.i"
	@echo "... lz4lib/lz4frame.s"
	@echo "... lz4lib/lz4hc.o"
	@echo "... lz4lib/lz4hc.i"
	@echo "... lz4lib/lz4hc.s"
	@echo "... lz4lib/xxhash.o"
	@echo "... lz4lib/xxhash.i"
	@echo "... lz4lib/xxhash.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

